// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Electrodomestico
{
    public short Codigo { get; set; }

    public short IdTipo { get; set; }

    public string Descripcion { get; set; }

    public virtual Tipo IdTipoNavigation { get; set; }
}