// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Tipo
{
    public short IdTipo { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Electrodomestico> Electrodomestico { get; } = new List<Electrodomestico>();
}