// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace TypeConfigurations
{
    public partial class ElectrodomesticoConfiguration : IEntityTypeConfiguration<Electrodomestico>
    {
        public void Configure(EntityTypeBuilder<Electrodomestico> entity)
        {
            entity.HasKey(e => e.Codigo).HasName("PK__Electrod__06370DADC9EF6CCE");

            entity.Property(e => e.Codigo).ValueGeneratedNever();
            entity.Property(e => e.Descripcion)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);

            entity.HasOne(d => d.IdTipoNavigation).WithMany(p => p.Electrodomestico)
            .HasForeignKey(d => d.IdTipo)
            .OnDelete(DeleteBehavior.ClientCascade)
            .HasConstraintName("FK_Electrodomestico_Tipo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Electrodomestico> entity);
    }
}
