// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace TypeConfigurations
{
    public partial class TipoConfiguration : IEntityTypeConfiguration<Tipo>
    {
        public void Configure(EntityTypeBuilder<Tipo> entity)
        {
            entity.HasKey(e => e.IdTipo).HasName("PK__Tipo__9E3A29A5881D3F55");

            entity.Property(e => e.IdTipo).ValueGeneratedNever();
            entity.Property(e => e.Descripcion)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Tipo> entity);
    }
}
